### ISSUE TITLE
UILocalNotification Deprecated

### ISSUE THREAD

**Issue by luliu** [Marketo/ios-sdk#13]
Hello, please update the SDK to support iOS 10 and above projects. 

```
../Pods/Marketo-iOS-SDK/Marketo.framework/Headers/Marketo.h:110:79: error: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest [-Werror,-Wdeprecated-declarations]
```

**Comment by mahtorohit** [comment]
Marketo SDK supports ios 10 already. Are you still getting this issue on latest MarketoSDK? Am Not getting this on my side can you please tell me what build target are you using. Also, have you tried installing via cocopod?
We do have  UNNotification support for MarketoSDK.

**Comment by caffeineflo** [comment]
@mahtorohit We're facing the exact same issue as @luliu . Marketo uses 'UILocalNotification' which is first deprecated with iOS 10. If you set your deployment target to iOS 10 and above, Xcode will give you warnings for these usages.

To be fully compatible and be future proof, Marketo would need to update it's SDK removing the usage of 'UILocalNotification' and move to 'UNNotificationRequest'

**Comment by mahtorohit** [comment]
@caffeineflo, Am not able to reproduce it on any of my available devices including ios 11.X. Can you provide more info on this?
About the UILocalNotification, Marketo ios SDK supports old ios versions as well so we could not remove UILocalNotification from code base but we did consider this case & it should not create any issues in latest ios versions except any deprecation warning which should be ignored.

**Comment by caffeineflo** [comment]
@mahtorohit 
As mentioned in my comment you would have to set the DEPLOYMENT TARGET to iOS 10 or above. This has little to do with devices iOS version. It is not possible you're not seeing this issue, otherwise Xcode and the iPhone SDK would be seriously broken.

Nobody says you have to drop old iOS versions, all you have to do is provide an additional API for `UNNotificationRequest` so that your users supporting iOS 10 or above won't have this deprecation warning. Even further, if Apple deprecates `UILocalNotification` we won't be able to use Marketo anymore.

**Comment by mahtorohit** [comment]
@caffeineflo As suggested, will need more info on this (Marketo SDK version, Xcode version, with or without cocopod) as we are not able to reproduce this.
Please make sure you are using the latest Marketo SDK, Please try [this](http://developers.marketo.com/mobile/installation/) documentation, if it helps.
If you are a Marketo Customer, You can get in touch with the support team for the resolution.

**Comment by caffeineflo** [comment]
https://developer.apple.com/documentation/uikit/uilocalnotification
> iOS 4.0–10.0Deprecated

I guess Apple is wrong here. I just hope Marketo will help them soon to realize that their deprecation is wrong as they can't "reproduce".

**Comment by mahboud** [comment]
Has this been fixed?

**Comment by skharemarketo** [comment]
Hello @mahboud , can you please share asked details before, or a sample source code with the same configuration, it will help us in finding the root cause. More over as @mahtorohit suggested you can also get in touch with the Marketo support team. It help us in getting more details about the problem at our end.
